import { getActiveBanks, getActiveProducts, getLiveOrders, getServiceSettings, getActivePopups } from '../lib/db';
import { getNotices, formatNoticeDate } from '../lib/notice-db';
import ApplyForm from './components/ApplyForm';
import OrderLookup from './components/OrderLookup';
import SitePopups from './components/SitePopups';
import ProductRateSection from './components/ProductRateSection';
import HomeStatusBoard from './components/HomeStatusBoard';
import BrandLogo from './components/BrandLogo';
import ProductCashMenu from './components/ProductCashMenu';

const productImages={cultureland:'/images/products/%EC%BB%AC%EC%B3%90%EB%9E%9C%EB%93%9C%20%EB%AC%B8%ED%99%94%EC%83%81%ED%92%88%EA%B6%8C.svg','online-culture':'/images/products/%EC%98%A8%EB%9D%BC%EC%9D%B8%EB%AC%B8%ED%99%94%EC%83%81%ED%92%88%EA%B6%8C.jpg','cultureland-exchange':'/images/products/%EC%BB%AC%EC%B3%90%EB%9E%9C%EB%93%9C%20%EA%B5%90%ED%99%98%EA%B6%8C.png',teencash:'/images/products/%ED%8B%B4%EC%BA%90%EC%8B%9C.png','booknlife-book':'/images/products/%EB%B6%81%EC%95%A4%EB%9D%BC%EC%9D%B4%ED%94%84%20%EB%8F%84%EC%84%9C%EB%AC%B8%ED%99%94%EC%83%81%ED%92%88%EA%B6%8C.svg','booknlife-exchange':'/images/products/%EB%B6%81%EC%95%A4%EB%9D%BC%EC%9D%B4%ED%94%84%20%EB%8F%84%EC%84%9C%EB%AC%B8%ED%99%94%EC%83%81%ED%92%88%EA%B6%8C.svg','lotte-mobile':'/images/products/%EB%A1%AF%EB%8D%B0%EB%AA%A8%EB%B0%94%EC%9D%BC%EC%83%81%ED%92%88%EA%B6%8C.png','google-gift':'/images/products/%EA%B5%AC%EA%B8%80%EA%B8%B8%ED%94%84%ED%8A%B8%20%EC%B9%B4%EB%93%9C.svg'};
const steps=[['01','https://www.ksdl.kr/images/icon1.png','상품권 선택','보유한 상품권과 현재 매입률을 확인합니다.'],['02','https://www.ksdl.kr/images/icon2.png','신청정보 입력','PIN 번호, 계좌정보와 조회 비밀번호를 입력합니다.'],['03','https://www.ksdl.kr/images/icon3.png','상품권 검수','접수된 PIN의 사용 가능 여부와 권면금액을 확인합니다.'],['04','https://www.ksdl.kr/images/icon4.png','처리 완료','확인 결과에 따라 입금하고 처리상태를 안내합니다.']];
const notices=['신청 전 상품권 번호와 계좌·연락처 정보를 정확하게 확인해 주세요.','잘못 입력한 정보로 입금이 지연되거나 오입금이 발생한 경우, 입력 내용에 따라 추가 확인이 필요할 수 있습니다.','비정상적인 상품권 등록이나 허위 정보가 확인되면 안전한 거래를 위해 접수 또는 서비스 이용이 제한될 수 있습니다.','도난·사기 등 불법적인 경로로 취득한 상품권의 현금화를 시도할 경우 거래가 중단되며 관계기관의 확인 절차가 진행될 수 있습니다.','접수 및 거래 정보는 분쟁 처리와 법령상 의무 이행에 필요한 범위와 기간 동안 안전하게 보관한 뒤 파기합니다.','고객 정보는 거래 처리와 고객지원 등 고지된 목적 범위에서만 이용하며, 법령상 근거가 없는 제3자 제공은 하지 않습니다.'];
export const dynamic='force-dynamic';
export default async function Home(){const settings=await getServiceSettings();const[products,banks,liveOrders,popups,noticeRows]=await Promise.all([getActiveProducts(),getActiveBanks(),getLiveOrders(settings.liveOrderLimit),getActivePopups(5),getNotices({publishedOnly:true,limit:6})]);const safeProducts=products.map(p=>({id:Number(p.id),name:p.name,slug:p.slug,default_rate:Number(p.default_rate),imageUrl:productImages[p.slug]||p.image_url||''}));const safeBanks=banks.map(b=>({id:Number(b.id),name:b.name,code:b.code}));const safePopups=popups.map(p=>({id:Number(p.id),title:p.title||'',content:p.content||'',imageUrl:p.image_url||'',mobileImageUrl:p.mobile_image_url||'',linkUrl:p.link_url||''}));const safeLiveOrders=liveOrders.map(o=>{const product=safeProducts.find(p=>String(o.product_names||'').includes(p.name));return {order_no:o.order_no,customer_name:o.customer_name||'',product_names:o.product_names||'상품권',item_count:Number(o.item_count||1),status:o.status,imageUrl:product?.imageUrl||''}});const safeNotices=noticeRows.map(n=>({id:Number(n.id),title:n.title||'',date:formatNoticeDate(n.created_at)}));const fmt=new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'2-digit',month:'2-digit',day:'2-digit',weekday:'short'}).format(new Date());return <div className="sayo" id="top"><SitePopups popups={safePopups}/><header className="topbar"><div className="shell headerIn"><a className="logo imageLogo" href="#top"><BrandLogo/></a><nav><a href="#rates">상품권매입시세</a><a href="#live">실시간매입현황</a><a href="#guide">이용방법</a><ProductCashMenu/><a href="#faq">자주묻는질문</a><a href="#customer">고객센터</a></nav><a className="lookupBtn" href="#lookup">내주문조회</a></div></header><main>
<section className="heroBanner"><a href="#apply" aria-label="상품권 현금교환 신청하기"><picture><source media="(max-width:760px)" srcSet="/images/hero/mobilehero.webp"/><img src="/images/hero/pchero.webp" alt="사요 상품권 빠르고 안전한 상품권 매입 서비스" fetchPriority="high"/></picture></a></section>
<ProductRateSection products={safeProducts} rateNotice={settings.rateNotice} formattedDate={fmt}/>
<section id="apply" className="applySection"><div className="shell"><div className="sectionTitle"><p>상품권 현금교환</p><h2>상품권 정보를 입력하고 바로 신청하세요</h2></div><ApplyForm products={safeProducts} banks={safeBanks} settings={settings}/></div></section>
<section id="lookup" className="lookupSection"><div className="shell"><div className="sectionTitle"><p>내 주문 조회</p><h2>전화번호로 처리상태를 확인하세요</h2><span>접수 시 입력한 전화번호와 조회 비밀번호로 신청내역을 확인할 수 있습니다.</span></div><OrderLookup/></div></section>
<HomeStatusBoard orders={safeLiveOrders} notices={safeNotices}/>
<section id="guide" className="guideSection"><div className="shell"><div className="sectionTitle"><p>이용 절차</p><h2>신청부터 입금까지 4단계</h2></div><div className="stepGridKsdl">{steps.map(([n,img,t,d])=><article key={n}><span>{n}</span><div><img src={img} alt={t}/></div><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
<section className="customerNotice"><div className="shell"><div className="noticePanel"><div className="noticeHeading"><span className="noticeBell">♧</span><div><h2><em>꼭!</em> 알아두세요.</h2><p>안전한 거래를 위해 신청 전에 확인해 주세요.</p></div></div><ol>{notices.map((text,i)=><li key={text}><span>{String(i+1).padStart(2,'0')}.</span><p>{text}</p></li>)}</ol></div></div></section>
<section id="faq" className="faqKsdl"><div className="shell"><div className="sectionTitle"><p>이용 전 확인</p><h2>자주 묻는 질문</h2></div><div className="faqListKsdl"><details><summary>회원가입이 필요한가요?</summary><p>별도 회원가입 없이 신청할 수 있습니다.</p></details><details><summary>최소 판매 금액이 있나요?</summary><p>최소 판매금액은 {settings.minimumOrderAmount.toLocaleString()}원 이상입니다.</p></details><details><summary>접수한 주문은 어디에서 확인하나요?</summary><p>접수 시 입력한 전화번호와 조회 비밀번호로 확인할 수 있습니다.</p></details></div></div></section></main><footer id="customer"><div className="shell footerGrid"><div><a className="logo footerLogo imageLogo" href="#top"><BrandLogo className="footerBrandLogo"/></a><h3>안전한 접수와 정확한 처리를 약속드립니다.</h3>{settings.customerPhone&&<p>고객센터 {settings.customerPhone}{settings.customerHours&&` · ${settings.customerHours}`}</p>}{settings.customerEmail&&<p>{settings.customerEmail}</p>}</div><div className="business"><h4>사업자 정보</h4><p><span>상호</span><b>{settings.businessName}</b></p>{settings.businessOwner&&<p><span>대표자</span><b>{settings.businessOwner}</b></p>}{settings.businessNumber&&<p><span>사업자등록번호</span><b>{settings.businessNumber}</b></p>}{settings.businessAddress&&<p><span>주소</span><b>{settings.businessAddress}</b></p>}<p><span>도메인</span><b>seoyo.kr</b></p><p><a href="/terms">이용약관</a> · <a href="/privacy">개인정보처리방침</a></p></div></div></footer></div>}
